#kube-state-scrape.yaml

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: kube-state-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http   
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - monitoring